/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface GameCell {
        "alive": boolean;
        "cellId": number;
    }
    interface GameOfLife {
    }
}
declare global {
    interface HTMLGameCellElement extends Components.GameCell, HTMLStencilElement {
    }
    var HTMLGameCellElement: {
        prototype: HTMLGameCellElement;
        new (): HTMLGameCellElement;
    };
    interface HTMLGameOfLifeElement extends Components.GameOfLife, HTMLStencilElement {
    }
    var HTMLGameOfLifeElement: {
        prototype: HTMLGameOfLifeElement;
        new (): HTMLGameOfLifeElement;
    };
    interface HTMLElementTagNameMap {
        "game-cell": HTMLGameCellElement;
        "game-of-life": HTMLGameOfLifeElement;
    }
}
declare namespace LocalJSX {
    interface GameCell {
        "alive"?: boolean;
        "cellId"?: number;
    }
    interface GameOfLife {
    }
    interface IntrinsicElements {
        "game-cell": GameCell;
        "game-of-life": GameOfLife;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "game-cell": LocalJSX.GameCell & JSXBase.HTMLAttributes<HTMLGameCellElement>;
            "game-of-life": LocalJSX.GameOfLife & JSXBase.HTMLAttributes<HTMLGameOfLifeElement>;
        }
    }
}
